name: Testing

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: denolib/setup-deno@v2
        with:
          deno-version: v1.8
      - name: Create coverage files
        run: deno test --unstable --coverage=coverage # create coverage files
      - name: Create coverage report
        run: deno --unstable coverage ./coverage --lcov > coverage.lcov # create coverage report
      - name: Collect coverage
        uses: codecov/codecov-action@v1.0.10 # upload the report on Codecov
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.lcov
